@startuml Annihialtion
Actor "Option and Anti-Option Holder" as Holder
participant "Smart Contract\nAnnihilate: ONLY BEFORE EXPIRATION" as annihilate

Holder-> annihilate: post option equal amount of option and anti-option tokens
annihilate -> Holder: get from deposit corresponding amount of underlying tokens

hide footbox
@enduml
