@startuml
actor "Option Line Creator" as creator
actor "Writer" as writer
actor "Auction Winner" as auction_winner
participant "OptionFactory" as req_handler
participant "OptionSerieVerifier" as verifier
participant "ERC721" as erc721
participant "Auction Contract" as auction
participant "Option Serie Contract" as opt_serie

creator -> req_handler: create request
req_handler -> verifier: verification of request
req_handler -> erc721: mint
erc721 -> req_handler: to 

req_handler -> auction: create auction
req_handler -> auction: transfer erc721 for auction

req_handler -> opt_serie: create option serie

writer -> opt_serie: write options and transfer fee

auction -> auction: defines a winner
auction  -> erc721: transfer ownership of erc721 token to winner
auction -> auction_winner: transfer ownership of erc721 token to auction winner
auction_winner -> req_handler: "claim" option serie ownership 

req_handler -> opt_serie: withdraw collected before claim fee amount went to creator
req_handler -> creator: 1/2 of collected before claim fee goes to creator
req_handler -> req_handler: remaining can be withdrawn by owner

writer -> opt_serie: write options and transfer fees
auction_winner -> req_handler: erc721 token owner can withdraw all collected fees 
req_handler -> opt_serie: via OptionFactory
@enduml
