@startuml
actor Buyer
participant "Smart Contract\nExercise: ONLY BEFORE EXPIRATION " as exec

Buyer -> exec: post option tokens and corresponding amount basis tokens
exec -> Buyer: get from smart contract corresponding amount of underlying tokens

hide footbox
@enduml
