@startuml
Actor "Anti-Option Holder" as Holder
participant "Smart Contract\nWithdraw: ONLY AFTER EXPIRATION" as withdraw

Holder -> withdraw: put anti-option tokens
withdraw -> Holder: get corresponding share amount of underlying and basis (from exercised) tokens

hide footbox
@enduml
