@startuml
:Writer: as Writer
(Write Options) as (write)
("mint" \n Options ERC20 Tokens) as (genOpts)
("mint" \n Anti-Options ERC20 Tokens) as (genAntiOpts)

Writer -down-> (write): deposit and \nlock underlying

(write) -left-> (genOpts)

(write) -right-> (genAntiOpts)

(genOpts) .up..> Writer: belongs to
(genAntiOpts) .up..> Writer: belongs to

(Sell Option Tokens) as sellOpts
(Sell Anti-Options Tokens) as sellAntiOpts

Writer -left-> sellOpts
sellOpts <-left- Buyer: get the rights to buy of underlying tokens\n at strike price before expiration
Writer -right-> sellAntiOpts
sellAntiOpts <-right- :Anti Option Buyer: :  gets the rights for\nthe locked underlying tokens

note bottom of (write)
interacts with OptionPair contact
which holds and controls deposited and exercised
basis and underlying tokens
end note

@enduml
